setwd("D:/ATAC-seq")

#______2.1_______________Differential ATACseq________________________________#



#For the second dataset we take ATACseq generated by Bing Ren at UCSD as part of the ENCODE consortium. It includes samples from several tissues in Mice. Links to data and sample information are included in list below.
#__________Liver day 12 - ENCSR302LIV (https://www.encodeproject.org/experiments/ENCSR302LIV/)
#_______________Kidney day 15 - ENCSR023QZX (https://www.encodeproject.org/experiments/ENCSR023QZX/)
#____________________Hindbrain day 12 - ENCSR088UYE (https://www.encodeproject.org/experiments/ENCSR088UYE/)



#Identifying non-redundant peaks (generate peak files similar to script 1.1)

peaks <- dir("D:/ATAC-seq/PeakDirectory/ATAC_50K_2/", pattern = "*.narrowPeak",
             full.names = TRUE)


myPeaks <- lapply(peaks, ChIPQC:::GetGRanges, simple = TRUE)
allPeaksSet_nR <- reduce(unlist(GRangesList(myPeaks)))
overlap <- list()
for (i in 1:length(myPeaks)) {
  overlap[[i]] <- allPeaksSet_nR %over% myPeaks[[i]]
}
overlapMatrix <- do.call(cbind, overlap)
colnames(overlapMatrix) <- basename(peaks)
mcols(allPeaksSet_nR) <- overlapMatrix

allPeaksSet_nR[1:2, ]

# blkList file: https://www.encodeproject.org/annotations/ENCSR636HFF/

blkList <- import.bed("ENCFF547MET.bed.gz")

nrToCount <- allPeaksSet_nR[
  !(allPeaksSet_nR %over% blkList)
]

# Check results
nrToCount
length(nrToCount)


#nrToCount <- allPeaksSet_nR[!allPeaksSet_nR %over% blkList & !seqnames(allPeaksSet_nR) %in%
"chrM"]
#nrToCount


# Counting for di erential ATACseq

library(Rsubread)
occurrences <- rowSums(as.data.frame(elementMetadata(nrToCount)))
nrToCount <- nrToCount[occurrences >= 2, ]
nrToCount

library(GenomicAlignments)
bamsToCount <- dir("~/Downloads/ATAC_Workshop/ATAC_Data/ATAC_BAM_forCounting/", full.names = TRUE,
                   pattern = "*.\\.bam$")

#myCounts <- summarizeOverlaps(consensusToCount, bamsToCount, singleEnd = FALSE)

myCounts <- summarizeOverlaps(
  features = nrToCount,
  reads = BamFileList(bamsToCount),
  mode = "Union",
  singleEnd = FALSE,
  ignore.strand = TRUE,
  fragments = TRUE
)


colnames(myCounts) <- c("HindBrain_1", "HindBrain_2", "Kidney_1", "Kidney_2", "Liver_1",
                        "Liver_2")
save(myCounts, file = "myCounts.RData")

#DESeq2 for differential ATACseq: Metadata & DESeq2
library(DESeq2)
load("myCounts.RData")
Group <- factor(c("HindBrain", "HindBrain", "Kidney", "Kidney", "Liver", "Liver"))
metaData <- data.frame(Group, row.names = colnames(myCounts))

atacDDS <- DESeqDataSetFromMatrix(assay(myCounts), metaData, ~Group, rowRanges = rowRanges(myCounts))
atacDDS <- DESeq(atacDDS)

KidneyMinusHindbrain <- results(atacDDS, c("Group", "Kidney", "HindBrain"), format = "GRanges")
KidneyMinusHindbrain <- KidneyMinusHindbrain[order(KidneyMinusHindbrain$pvalue)]
KidneyMinusHindbrain

res_GR <- GRanges(KidneyMinusHindbrain)

#Filter significant peaks near promoters
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
toOverLap <- promoters(TxDb.Mmusculus.UCSC.mm10.knownGene, 500, 500)
KidneyMinusHindbrain <- KidneyMinusHindbrain[(!is.na(KidneyMinusHindbrain$padj) &
                                                KidneyMinusHindbrain$padj < 0.05) & KidneyMinusHindbrain %over% toOverLap, ]

myReport <- makebedtable(KidneyMinusHindbrain, "KidneyMinusHindbrain.html", getwd())
browseURL(myReport)


#Annotation for differential ATACseq
anno_KidneyMinusHindbrain <- annotatePeak(KidneyMinusHindbrain, TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene,
                                          verbose = FALSE)
DB_ATAC <- as.data.frame(anno_KidneyMinusHindbrain)
DB_ATAC[1, ]

library(clusterProfiler)
go <- enrichGO(DB_ATAC$geneId, OrgDb = "org.Mm.eg.db", ont = "BP", maxGSSize = 5000)
go[1:2, 1:6]





# -------------------------------
#Explore MotifDb
# -------------------------------
library(MotifDb)
MotifDb

class(MotifDb)
length(MotifDb)
MotifDb[1]

MotifDb[[1]]
colSums(MotifDb[[1]])
values(MotifDb)[1:2, ]

#We can use the query function to subset our MotifList by infomation in the metadata.
#CTCF: CCCTC-binding factor: # Query for specific TF

CTCFMotifs <- query(MotifDb, "CTCF")
CTCFMotifs
#For more specific queries
CTCFMotifs <- query(MotifDb, c("CTCF", "hsapiens", "jaspar2018"))
CTCFMotifs

# -------------------------------
#Get motifs from JASPAR2020
# -------------------------------

library(JASPAR2020)
JASPAR2020

library(TFBSTools)
`?`(getMatrixByID)

GATA2mat <- getMatrixByName(JASPAR2020, "GATA2")
class(GATA2mat)

GATA2mat <- getMatrixByID(JASPAR2020, "MA0036.2")
ID(GATA2mat)

myMatrix <- Matrix(GATA2mat)
myMatrixToo <- as.matrix(myMatrix)
myMatrix

opts <- list()
opts[["collection"]] <- "CORE"
opts[["tax_group"]] <- "vertebrates"
motifList <- getMatrixSet(JASPAR2020, opts)

# -------------------------------
#Visualize motifs
# -------------------------------

library(seqLogo)
CTCFMotifs <- query(MotifDb, "CTCF")
seqLogo::seqLogo(CTCFMotifs[[1]], ic.scale = FALSE)

seqLogo::seqLogo(CTCFMotifs[[1]])

myMatrix

ppm <- myMatrix/colSums(myMatrix)
ppm

seqLogo::seqLogo(ppm)

GATA2_IC <- toICM(GATA2mat)
TFBSTools::seqLogo(GATA2_IC)

library(ggseqlogo)
library(ggplot2)
ggseqlogo(myMatrix) + theme_minimal()


# -------------------------------
#Prepare ATAC-seq peaks- Identifying Motifs in ATAC
# -------------------------------

opts <- list()
opts[["tax_group"]] <- "vertebrates"
opts[["collection"]] <- "CORE"
opts[["all_versions"]] <- FALSE
motifsToScan <- getMatrixSet(JASPAR2020, opts)

load("myCounts.RData")
myCounts
peakRanges <- rowRanges(myCounts)
peakRanges[1, ]
library(BSgenome.Mmusculus.UCSC.mm10)
peakRangesCentered <- resize(peakRanges, fix = "center", width = 100)
peakSeqs <- getSeq(BSgenome.Mmusculus.UCSC.mm10, peakRangesCentered)
names(peakSeqs) <- as.character(peakRangesCentered)
peakSeqs

# -------------------------------
#Match motifs in peaks
# -------------------------------

# Positions
motif_positions <- matchMotifs(motifsToScan[1:4], peakSeqs[1:100], out = "positions")
class(motif_positions)

motif_positions$MA0029.1

MA0029hits <- motif_positions$MA0029.1
names(MA0029hits) <- names(peakSeqs[1:100])
unlist(MA0029hits, use.names = TRUE)

#Finding motif hits- Binary matches matrix
motifHits <- matchMotifs(motifsToScan, peakSeqs, out = "matches")
class(motifHits)
motifHits
mmMatrix <- motifMatches(motifHits)
dim(mmMatrix)
mmMatrix[1:8, 1:8]

totalMotifOccurence <- colSums(mmMatrix)
totalMotifOccurence[1:4]

# Peaks containing specific motif
peaksWithMA0912 <- peakRangesCentered[mmMatrix[, "MA0912.2"] == 1]
peaksWithMA0912

# -------------------------------
#chromVAR analysis
# -------------------------------
library(chromVAR)

# Filter low-count peakss
#Setting up for chromVar
myCounts <- myCounts[rowSums(assay(myCounts)) > 5, ]

#Correct GC bias
myCounts <- addGCBias(myCounts, genome = BSgenome.Mmusculus.UCSC.mm10)


# Match motifs in filtered peaks
#ID motifs in peaks
motif_ix <- matchMotifs(motifsToScan, myCounts, genome = BSgenome.Mmusculus.UCSC.mm10)
motif_ix

# Compute deviations and variability
deviations <- computeDeviations(object = myCounts, annotations = motif_ix)
variability_Known <- computeVariability(deviations)

# -------------------------------
#Inspect chromVAR results
# -------------------------------

devZscores <- deviationScores(deviations)
devZscores[1:2, ]

#chromVar variability
variability_Known <- variability_Known[order(variability_Known$p_value), ]
variability_Known[1:10, ]
topVariable <- variability_Known[1:20, ]

# Merge top variable TFs with deviations
devTop <- merge(topVariable[, 1, drop = FALSE], devZscores, by = 0)
devTop[1:2, ]

devToPlot <- as.matrix(devTop[, -c(1:2)])
rownames(devToPlot) <- devTop[, 2]

# -------------------------------
#Plot heatmap of chromVAR deviations
# -------------------------------

library(pheatmap)
#pheatmap(devToPlot)

pheatmap(devToPlot, cluster_rows = TRUE, cluster_cols = TRUE,
         show_rownames = TRUE, show_colnames = TRUE,
         scale = "row")



